MvcPL/Controllers/TestResultController.cs
using System.Linq;
using System.Web.Mvc;
using MvcPL.Models;
using PagedList;
using BLL.Interfaces;
using MvcPL.Infrastructure.Mappers;

namespace MvcPL.Controllers
{
    /// <summary>
    /// Provides methods that respond to HTTP requests for test results.
    /// </summary>
    [Authorize]
    public class TestResultController : Controller
    {
        #region Fields
        private readonly ITestResultService service;
        #endregion

        #region Constructors
        /// <summary>
        /// Instanciates TestResultController with specified parameters.
        /// </summary>
        /// <param name="service"> TestResultService instance.</param>
        public TestResultController(ITestResultService service)
        {
            this.service = service;
        }
        #endregion

        #region Actions
        /// <summary>
        /// Displays test results for specified user.
        /// </summary>
        /// <param name="userName"> User email.</param>
        /// <param name="pageNumber"> Page number.</param>
        /// <returns> TestResult view.</returns>
        public ActionResult TestResult(string userName, int? pageNumber)
        {
            var testResults = service.GetTestResultsByUser(userName).Select(tr => tr.ToTestResultViewModel());
            return View(testResults.ToPagedList(pageNumber ?? 1, 10));
        }

        /// <summary>
        /// Displays test result after completing the test.
        /// </summary>
        /// <param name="testResult"> TestResultViewModel instance.</param>
        /// <returns> TestingResult view.</returns>
        public ActionResult TestingResult(TestResultViewModel testResult)
        {
            return View(testResult);
        }
        #endregion
    }
}

MvcPL/Controllers/UserController.cs
using MvcPL.Models;
using System.Linq;
using System.Web.Mvc;
using PagedList;
using BLL.Interfaces;
using MvcPL.Infrastructure.Mappers;

namespace MvcPL.Controllers
{
    /// <summary>
    /// Provides methods that respond to HTTP requests for user management.
    /// </summary>
    [Authorize]
    public class UserController : Controller
    {
        #region Fields
        private readonly IUserService userService;
        private readonly IRoleService roleService;
        #endregion

        #region Constructors
        /// <summary>
        /// Instanciates UserController with specified parameters.
        /// </summary>
        /// <param name="userService"> UserService instance.</param>
        /// <param name="roleService"> RoleService instance.</param>
        public UserController(IUserService userService, IRoleService roleService)
        {
            this.userService = userService;
            this.roleService = roleService;
        }
        #endregion

        #region Actions
        /// <summary>
        /// Displays user information for given user name.
        /// </summary>
        /// <param name="userName"> User email.</param>
        /// <returns> Details view.</returns>
        public ActionResult UserDetails(string userName)
        {
            var user = userService.GetUserByEmail(userName)?.ToUserViewModel();
            if (user == null) return RedirectToAction("NotFound", "Error");
            return View("Details", user);
        }

        /// <summary>
        /// Displays list of users.
        /// </summary>
        /// <param name="pageNumber"> Page number.</param>
        /// <returns> Index view.</returns>
        public ActionResult Index(int? pageNumber)
        {
            var users = userService.GetAllUsers().Select(u => u.ToUserViewModel());
            return View(users.ToPagedList(pageNumber ?? 1, 10));
        }

        /// <summary>
        /// Displays user information for given user id.
        /// </summary>
        /// <param name="id"> User identificator.</param>
        /// <returns> Details view.</returns>
        public ActionResult Details(int id)
        {
            UserViewModel user = null;
            try
            {
                user = userService.GetUser(id)?.ToUserViewModel();
            }
            catch
            {
                return RedirectToAction("Error", "Error");
            }
            if (user == null) RedirectToAction("Error", "Error");
            return View(user);
        }

        /// <summary>
        /// Displays user editor.
        /// </summary>
        /// <param name="id"> User identificator.</param>
        /// <returns> Edit view.</returns>
        public ActionResult Edit(int id)
        {
            var roles = roleService.GetAllRoles().Select(r => r.ToRoleViewModel());
            UserViewModel user = null;
            try
            {
                user = userService.GetUser(id)?.ToUserViewModel();
            }
            catch
            {
                return RedirectToAction("Error", "Error");
            }
            if (user == null) return RedirectToAction("Error", "Error");
            foreach (var role in user.Roles) role.IsSelected = true;
            foreach (var role in roles) if (user.Roles.Where(r => r.Id == role.Id).SingleOrDefault() == null) user.Roles.Add(role);
            return View(user);
        }

        /// <summary>
        /// Post user values.
        /// </summary>
        /// <param name="user"> UserViewModel instance.</param>
        /// <returns> Redirects to list of users.</returns>
        [HttpPost]
        public ActionResult Edit(UserViewModel user)
        {
            if (ModelState.IsValid)
            {
                var temp = user.Roles.ToList();
                temp.RemoveAll(r => r.IsSelected == false);
                user.Roles = temp;
                try
                {
                    userService.UpdateUser(user.ToBllUser());
                }
                catch
                {
                    return RedirectToAction("Error", "Error");
                }
                return RedirectToAction("Index");
            }
            return View(user);
        }

        /// <summary>
        /// Displays user delete form.
        /// </summary>
        /// <param name="id"> User identificator.</param>
        /// <returns> Delete view.</returns>
        public ActionResult Delete(int id)
        {
            UserViewModel user = null;
            try
            {
                user = userService.GetUser(id)?.ToUserViewModel();
            }
            catch
            {
                return RedirectToAction("Error", "Error");
            }
            if (user == null) RedirectToAction("Error", "Error");
            return View(user);
        }

        /// <summary>
        /// Deletes user.
        /// </summary>
        /// <param name="user"> UserViewModel instance.</param>
        /// <returns> Redirects to user list.</returns>
        [HttpPost]
        public ActionResult Delete(UserViewModel user)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    userService.DeleteUser(user.ToBllUser());
                }
                catch
                {
                    return RedirectToAction("Error", "Error");
                }
                return RedirectToAction("Index");
            }
            return View(user);
        }
        #endregion
    }
}

MvcPL/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <div style="display:block;float:right;">
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MvcPL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Knowledge Tesdting System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Knowledge Testing System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (User.IsInRole("Administrator"))
                    {
                        <li>@Html.ActionLink("Manage Users", "Index", "User")</li>
                        <li>@Html.ActionLink("Statistics", "Statistic", "Statistics")</li>
                    }
                </ul>
                <div style="display:block;float:right;">
                    @if (Request.IsAuthenticated)
                    {
                        @Html.ActionLink("My Results", "TestResult", "TestResult", new { userName = User.Identity.Name }, new { @class = "navbar-brand" })
                    }
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Knowledge Tesdting System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>