MvcPL/Models/UserViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using MvcPL.Infrastructure.Validation;

namespace MvcPL.Models
{
    /// <summary>
    /// Represents user.
    /// </summary>
    public class UserViewModel
    {
        /// <summary>
        /// Gets or sets User identificator.
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// User Name.
        /// </summary>
        /// <summary>
        /// Gets or sets Role Name.
        /// </summary>
        [Required]
        [MaxLength(100)]
        public string Name { get; set; }
        /// <summary>
        /// Gets or sets User Last Name.
        /// </summary>
        /// <summary>
        /// Gets or sets Role Name.
        /// </summary>
        [Required]
        [MaxLength(100)]
        public string LastName { get; set; }
        /// <summary>
        /// Gets or sets User e-mail address.
        /// </summary>
        /// <summary>
        /// Gets or sets Role Name.
        /// </summary>
        [Required]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "Invalid email.")]
        public string Email { get; set; }
        /// <summary>
        /// Gets or sets User phone number.
        /// </summary>
        [Required]
        [StringLength(100, ErrorMessage = "The password must contain at least {2} characters", MinimumLength = 8)]
        public string Password { get; set; }

        /// <summary>
        /// Gets or sets user roles.
        /// </summary>
        [RequiredProperty("IsSelected", true, ErrorMessage = "User must be in at least one role!")]
        public ICollection<RoleViewModel> Roles { get; set; }
    }
}

MvcPL/Controllers/RoleController.cs
using BLL;
using Logger;
using MvcPL.Models;
using System.Web.Mvc;
using BLL.Interfaces;
using MvcPL.Infrastructure.Mappers;

namespace MvcPL.Controllers
{
    /// <summary>
    /// Provides methods that respond to HTTP requests for role management.
    /// </summary>
    [Authorize]
    public class RoleController : Controller
    {
        #region Fields
        private readonly IRoleService service;
        private readonly ILogger logger = LogManager.GetLogger();
        #endregion

        #region Constructors
        /// <summary>
        /// Instanciates RoleController with required parameters.
        /// </summary>
        /// <param name="service"> RoleService instance.</param>
        public RoleController(IRoleService service)
        {
            this.service = service;
        }
        #endregion

        #region Actions
        /// <summary>
        /// Displays role creation form.
        /// </summary>
        /// <returns> Create view.</returns>
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Creates new role.
        /// </summary>
        /// <param name="role"> Role to create.</param>
        /// <returns> Redirects to list of users.</returns>
        [HttpPost]
        public ActionResult Create(RoleViewModel role)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    service.CreateRole(role.ToBllRole());
                }
                catch (RoleAlreadyExistsException ex)
                {
                    logger.Error("Role already exists.", ex);
                    ModelState.AddModelError("", "Role already exists.");
                    return View(role);
                }
                catch
                {
                    return RedirectToAction("Error", "Error");
                }
                return RedirectToAction("Index", "User");
            }
            return View(role);
        }
        #endregion
    }
}

MvcPL/Controllers/UserController.cs
using MvcPL.Models;
using System.Linq;
using System.Web.Mvc;
using PagedList;
using BLL.Interfaces;
using MvcPL.Infrastructure.Mappers;

namespace MvcPL.Controllers
{
    /// <summary>
    /// Provides methods that respond to HTTP requests for user management.
    /// </summary>
    [Authorize]
    public class UserController : Controller
    {
        #region Fields
        private readonly IUserService userService;
        private readonly IRoleService roleService;
        #endregion

        #region Constructors
        /// <summary>
        /// Instanciates UserController with specified parameters.
        /// </summary>
        /// <param name="userService"> UserService instance.</param>
        /// <param name="roleService"> RoleService instance.</param>
        public UserController(IUserService userService, IRoleService roleService)
        {
            this.userService = userService;
            this.roleService = roleService;
        }
        #endregion

        #region Actions
        /// <summary>
        /// Displays user information for given user name.
        /// </summary>
        /// <param name="userName"> User email.</param>
        /// <returns> Details view.</returns>
        public ActionResult UserDetails(string userName)
        {
            var user = userService.GetUserByEmail(userName)?.ToUserViewModel();
            if (user == null) return RedirectToAction("NotFound", "Error");
            return View("Details", user);
        }

        /// <summary>
        /// Displays list of users.
        /// </summary>
        /// <param name="pageNumber"> Page number.</param>
        /// <returns> Index view.</returns>
        public ActionResult Index(int? pageNumber)
        {
            var users = userService.GetAllUsers().Select(u => u.ToUserViewModel());
            return View(users.ToPagedList(pageNumber ?? 1, 10));
        }

        /// <summary>
        /// Displays user information for given user id.
        /// </summary>
        /// <param name="id"> User identificator.</param>
        /// <returns> Details view.</returns>
        public ActionResult Details(int id)
        {
            UserViewModel user = null;
            try
            {
                user = userService.GetUser(id)?.ToUserViewModel();
            }
            catch
            {
                return RedirectToAction("Error", "Error");
            }
            if (user == null) RedirectToAction("Error", "Error");
            return View(user);
        }

        /// <summary>
        /// Displays user editor.
        /// </summary>
        /// <param name="id"> User identificator.</param>
        /// <returns> Edit view.</returns>
        public ActionResult Edit(int id)
        {
            var roles = roleService.GetAllRoles().Select(r => r.ToRoleViewModel());
            UserViewModel user = null;
            try
            {
                user = userService.GetUser(id)?.ToUserViewModel();
            }
            catch
            {
                return RedirectToAction("Error", "Error");
            }
            if (user == null) return RedirectToAction("Error", "Error");
            foreach (var role in user.Roles) role.IsSelected = true;
            foreach (var role in roles) if (user.Roles.Where(r => r.Id == role.Id).SingleOrDefault() == null) user.Roles.Add(role);
            return View(user);
        }

        /// <summary>
        /// Post user values.
        /// </summary>
        /// <param name="user"> UserViewModel instance.</param>
        /// <returns> Redirects to list of users.</returns>
        [HttpPost]
        public ActionResult Edit(UserViewModel user)
        {
            if (ModelState.IsValid)
            {
                var temp = user.Roles.ToList();
                temp.RemoveAll(r => r.IsSelected == false);
                user.Roles = temp;
                try
                {
                    userService.UpdateUser(user.ToBllUser());
                }
                catch
                {
                    return RedirectToAction("Error", "Error");
                }
                return RedirectToAction("Index");
            }
            return View(user);
        }

        /// <summary>
        /// Displays user delete form.
        /// </summary>
        /// <param name="id"> User identificator.</param>
        /// <returns> Delete view.</returns>
        public ActionResult Delete(int id)
        {
            UserViewModel user = null;
            try
            {
                user = userService.GetUser(id)?.ToUserViewModel();
            }
            catch
            {
                return RedirectToAction("Error", "Error");
            }
            if (user == null) RedirectToAction("Error", "Error");
            return View(user);
        }

        /// <summary>
        /// Deletes user.
        /// </summary>
        /// <param name="user"> UserViewModel instance.</param>
        /// <returns> Redirects to user list.</returns>
        [HttpPost]
        public ActionResult Delete(UserViewModel user)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    userService.DeleteUser(user.ToBllUser());
                }
                catch
                {
                    return RedirectToAction("Error", "Error");
                }
                return RedirectToAction("Index");
            }
            return View(user);
        }
        #endregion
    }
}

MvcPL/Views/User/Delete.cshtml
@model MvcPL.Models.UserViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this User?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Roles)
        </dt>

        <dd>
            @string.Join(",", Model.Roles.Select(r => r.Name))
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.Roles)
        <div class="form-actions no-color">
            @Html.SubmitButton("Delete", "btn btn-default") |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MvcPL/Views/User/Details.cshtml
@model MvcPL.Models.UserViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>User details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Roles)
        </dt>

        <dd>
            @string.Join(",", Model.Roles.Select(r => r.Name))
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcPL/Views/User/Edit.cshtml
@model MvcPL.Models.UserViewModel
@using MvcPL.Models;

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit User</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Roles, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Roles, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Roles, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.SubmitButton("Save", "btn btn-default")
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MvcPL/Views/User/Index.cshtml
@model IPagedList<MvcPL.Models.UserViewModel>
@using PagedList;
@using PagedList.Mvc;

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{
    ViewBag.Title = "Index";
}

<h2>User Management</h2>

<div style="display:block;float:right;">
    <a href="@Url.Action("Create", "Role")" class="btn btn-success">
        Add new role
        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
    </a>
</div>
<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Roles)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @string.Join(",", item.Roles.Select(r => r.Name))
        </td>
        <td>
            <a href="@Url.Action("Edit", new { id = item.Id })">
                <i class="glyphicon glyphicon-pencil"></i>
                <span class="sr-only">Edit</span>
            </a>
            <a href="@Url.Action("Details", new { id = item.Id })">
                <i class="glyphicon glyphicon-expand"></i>
                <span class="sr-only">Details</span>
            </a>
            <a href="@Url.Action("Delete", new { id = item.Id })">
                <i class="glyphicon glyphicon-remove"></i>
                <span class="sr-only">Details</span>
            </a>
        </td>
    </tr>
}

</table>

@if (Model.PageCount > 1)
{
    @Html.PagedListPager(Model, pageNumber => Url.Action("Index", new { pageNumber }))
}
<p>
    @Html.ActionLink("Home", "Index", "Home")
</p>