MvcPL/Controllers/HomeController.cs
using System.Web.Mvc;

namespace MvcPL.Controllers
{
    /// <summary>
    /// Provides methods that respond to HTTP requests for anonymous users.
    /// </summary>
    [AllowAnonymous]
    public class HomeController : Controller
    {
        #region Actions
        /// <summary>
        /// Displays Index page.
        /// </summary>
        /// <returns> Index View.</returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Displays About page.
        /// </summary>
        /// <returns> About View.</returns>
        public ActionResult About()
        {
            return View();
        }

        /// <summary>
        /// Displays Contact page.
        /// </summary>
        /// <returns> Contact View.</returns>
        public ActionResult Contact()
        {
            return View();
        }
        #endregion
    }
}

MvcPL/Controllers/SubjectController.cs
using System.Linq;
using System.Web.Mvc;
using PagedList;
using BLL.Interfaces;
using MvcPL.Infrastructure.Mappers;

namespace MvcPL.Controllers
{
    /// <summary>
    /// Provides methods that respond to HTTP requests for test subjects.
    /// </summary>
    [Authorize]
    public class SubjectController : Controller
    {
        #region Fields
        private readonly ISubjectService subjectService;
        #endregion

        #region Constructors
        /// <summary>
        /// Instanciates SubjectController with specified parameters.
        /// </summary>
        /// <param name="subjectService"></param>
        public SubjectController(ISubjectService subjectService)
        {
            this.subjectService = subjectService;
        }
        #endregion

        #region Actions
        /// <summary>
        /// Displays Index page.
        /// </summary>
        /// <returns> Index View.</returns>
        [ChildActionOnly]
        public ActionResult Index(int? pageNumber)
        {
            var subjects = subjectService.GetAllSubjects().Select(s => s.ToSubjectViewModel());
            return PartialView(subjects.ToPagedList(pageNumber ?? 1, 10));
        }
        #endregion
    }
}

MvcPL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>
    This site functions as a knowledge testing system
    and provides tests on various subjects for users to complete.
    Application was developped withe the use of Microsoft Asp.Net MVC 5 technology by Philip Kozlov.
</p>

MvcPL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    You can contact me at
    <abbr title="Phone">P:</abbr>
    +375298560338
</address>

<address>
    <strong>Send me email at:</strong>   <a href="mailto:Support@example.com">philip.g.kozlov@gmail.com</a><br />
</address>

MvcPL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Welcome";
}

<h2>@ViewBag.Title.</h2>

@if (Request.IsAuthenticated)
{
    @Html.Action("Index", "Subject")
}
else
{
    <p>
       Welcome to Knowledge Testing System. 
       You can test you knowledge in various subjects by completing tests.
       In order to do so you must first @Html.ActionLink("log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" }) or 
       @Html.ActionLink("register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" }).
    </p>
}